# Generated by cucumber-sinatra. (2013-12-24 21:49:58 +1100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'streamer.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Streamer

class StreamerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  StreamerWorld.new
end
