test:
  sessions:
    default:
      database: interactive_painter_test
      hosts:
        - localhost:27017
  options:
    allow_dynamic_fields: false
    raise_not_found_error: false
development:
  sessions:
    default:
      database: interactive_painter
      hosts:
        - localhost:27017
  options:
    allow_dynamic_fields: false
    raise_not_found_error: false
production:
  sessions:
    default:
      database: ENV['MONGOLAB_DB']
      hosts:
        - ENV['MONGOLAB_URI']
  options:
    allow_dynamic_fields: false
    raise_not_found_error: false

