test:
  sessions:
    default:
      uri: mongodb://localhost:27017/interactive_painter_test
  options:
    allow_dynamic_fields: false
    raise_not_found_error: false
development:
  sessions:
    default:
      uri: mongodb://localhost:27017/interactive_painter
  options:
    allow_dynamic_fields: false
    raise_not_found_error: false
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
  options:
    allow_dynamic_fields: false
    raise_not_found_error: false
    skip_version_check: true
